// vga_sink.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module vga_sink (
		input  wire        clk_clk,                //      clk.clk
		input  wire        reset_reset_n,          //    reset.reset_n
		output wire        vga_CLK,                //      vga.CLK
		output wire        vga_HS,                 //         .HS
		output wire        vga_VS,                 //         .VS
		output wire        vga_BLANK,              //         .BLANK
		output wire        vga_SYNC,               //         .SYNC
		output wire [7:0]  vga_R,                  //         .R
		output wire [7:0]  vga_G,                  //         .G
		output wire [7:0]  vga_B,                  //         .B
		input  wire [29:0] video_in_data,          // video_in.data
		input  wire        video_in_startofpacket, //         .startofpacket
		input  wire        video_in_endofpacket,   //         .endofpacket
		input  wire        video_in_valid,         //         .valid
		output wire        video_in_ready          //         .ready
	);

	vga_sink_video_vga_controller_0 video_vga_controller_0 (
		.clk           (clk_clk),                //                clk.clk
		.reset         (~reset_reset_n),         //              reset.reset
		.data          (video_in_data),          //    avalon_vga_sink.data
		.startofpacket (video_in_startofpacket), //                   .startofpacket
		.endofpacket   (video_in_endofpacket),   //                   .endofpacket
		.valid         (video_in_valid),         //                   .valid
		.ready         (video_in_ready),         //                   .ready
		.VGA_CLK       (vga_CLK),                // external_interface.export
		.VGA_HS        (vga_HS),                 //                   .export
		.VGA_VS        (vga_VS),                 //                   .export
		.VGA_BLANK     (vga_BLANK),              //                   .export
		.VGA_SYNC      (vga_SYNC),               //                   .export
		.VGA_R         (vga_R),                  //                   .export
		.VGA_G         (vga_G),                  //                   .export
		.VGA_B         (vga_B)                   //                   .export
	);

endmodule
