# Write the Mel weights for audio_features to rtl/mel_weights.svh.
# Use the course Mel formula: hz2mel(f) = 2595*log10(1+f/700).
import math
SR, FRAME, NMEL, FMIN, FMAX, WBITS = 12000, 1024, 24, 100.0, 6000.0, 8
NB = FRAME//2 + 1                      # 513 positive bins
hz2mel = lambda f: 2595.0*math.log10(1.0 + f/700.0)
mel2hz = lambda m: 700.0*(10.0**(m/2595.0) - 1.0)
m0, m1 = hz2mel(FMIN), hz2mel(FMAX)
ctr = [mel2hz(m0 + (m1-m0)*i/(NMEL+1))*FRAME/SR for i in range(NMEL+2)]

# Split each bin across up to two nearby bands with weights that add to 1.
# Save the upper band and weight; the lower weight is 1 minus that weight.
rom = []
for b in range(NB):
    up, w = 31, 0                      # 31 = outside the bank, skip
    for m in range(NMEL+1):
        if ctr[m] < b <= ctr[m+1]:
            up = m
            w  = min(int(round((b-ctr[m])/(ctr[m+1]-ctr[m])*(1 << WBITS))), (1 << WBITS)-1)
            break
    rom.append((up, w))

with open('rtl/mel_weights.svh', 'w') as f:
    f.write("// GENERATED by tools/gen_mel.py -- do not edit by hand.\n")
    f.write(f"// {NMEL} Mel triangles, {FMIN:.0f}..{FMAX:.0f} Hz, {FRAME}-point FFT at {SR} Hz.\n")
    f.write("// Mel scale as the course notebook: hz2mel(f) = 2595*log10(1 + f/700).\n")
    f.write(f"// Per bin: MEL_UP = upper triangle index, MEL_W = its weight in Q0.{WBITS}.\n")
    f.write("// The lower triangle (MEL_UP-1) takes the complement 1-w, so the pair sums\n")
    f.write("// to 1.0 and ONE multiplier serves both bands. MEL_UP = 31 means skip.\n")
    f.write(f"localparam int MEL_BINS = {NB};\n")
    f.write("localparam logic [4:0] MEL_UP [0:%d] = '{%s};\n" % (NB-1, ",".join(str(u) for u,_ in rom)))
    f.write("localparam logic [%d:0] MEL_W  [0:%d] = '{%s};\n" % (WBITS, NB-1, ",".join(str(w) for _,w in rom)))
print("503 of 513 bins carry a weight; band widths 13..89 bins")
