"""Build saved HD templates from H95 features measured by the RTL, with held-out speakers."""
from pathlib import Path
import csv
import hashlib
import json
import shutil
import numpy as np
from provided_train_templates import kmeans_sad, write_svh
from template_common import decision
ROOT=Path(__file__).resolve().parents[1]
LABELS=['ee','ah','oo','aw']

def main():
    work=ROOT/'build/h95';manifest=json.loads((work/'manifest.json').read_text())
    by=[[] for _ in LABELS];test=[];rows=[];seen={}
    with (work/'features.csv').open() as stream:
        for row in csv.DictReader(stream):
            token=int(row['token_index']);record=manifest['records'][token]
            packed=int(row['feature'],16)
            feature=np.array([(packed>>(16*i))&65535 for i in range(24)],dtype=np.int64)
            seen[token]=seen.get(token,0)+1
            rows.append([record['token'],record['class'],record['split'],row['feature']])
            if record['split']=='train':by[record['class']].append(feature)
            else:test.append((record,feature))
    for i,record in enumerate(manifest['records']):
        if seen.get(i,0)!=record['frames']:raise ValueError('Missing frames: '+record['token'])
    templates=[]
    for frames in by:
        values=np.array(frames,dtype=np.int64)
        candidates=[np.rint(kmeans_sad(values.astype(float),4,seed=s,iters=40)).astype(np.int64) for s in range(12)]
        # Pick the seed using training error only; held-out speakers never select templates.
        templates.append(min(candidates,key=lambda centres:np.abs(values[:,None,:]-centres).sum(axis=2).min(axis=1).sum()))
    templates=np.array(templates)
    header=ROOT/'rtl/templates.svh'
    write_svh(str(header),templates.reshape(16,24),24)
    header.write_text('// Saved templates from real H95 vowel recordings; generated by tools/train_h95.py.\n'
      'localparam bit TEMPLATES_READY = 1;\nlocalparam int TEMPLATE_D = 24;\nlocalparam int TEMPLATE_NT = 4;\n'+header.read_text())
    (ROOT/'rtl/templates.hex').write_text(''.join(''.join(f'{int(v):04x}' for v in row[::-1])+'\n' for row in templates.reshape(16,24)))
    matrix=[[0]*5 for _ in LABELS];test_features=[];expected=[]
    for record,feature in test:
        result,reject,confidence=decision(feature,templates)
        matrix[record['class']][4 if reject else result]+=1
        test_features.append(''.join(f'{int(v):04x}' for v in feature[::-1]))
        # Store predicted class, reject flag and confidence for the RTL check.
        expected.append(f'{((result if not reject else 0)<<9)|(int(reject)<<8)|confidence:03x}')
    target=ROOT/'assets/h95';target.mkdir(exist_ok=True)
    shutil.copyfile(header,target/'templates.svh')
    (target/'heldout_features.hex').write_text('\n'.join(test_features)+'\n')
    (target/'heldout_expected.hex').write_text('\n'.join(expected)+'\n')
    (target/'test_dimensions.svh').write_text(f'localparam int H95_TEST_FRAMES={len(test)};\n')
    data=ROOT/'data/h95'
    shutil.copyfile(work/'manifest.json',data/'segments.json')
    with (data/'features.csv').open('w',newline='') as stream:
        writer=csv.writer(stream);writer.writerow(['token','class','split','feature']);writer.writerows(rows)
    accepted=sum(sum(row[:4]) for row in matrix);correct=sum(matrix[c][c] for c in range(4))
    report={'source':'data/h95/h95.zip','archive_sha256':manifest['archive_sha256'],
      'feature_mode':4,'dimensions':24,'log_scale':64,'templates_per_class':4,'rho':'7/10','dmax':65000,
      'labels':LABELS,'vowel_mapping':manifest['mapping'],'training_frames':[len(f) for f in by],
      'held_out_confusion_columns':LABELS+['reject'],'held_out_confusion':matrix,
      'held_out_frames':len(test),'accepted_accuracy':correct/max(accepted,1),
      'overall_correct_fraction':correct/len(test),'rejection_fraction':1-accepted/len(test),
      'split':manifest['split'],'feature_extraction':'Actual audio_frontend -> course FFT -> fft_mag_sq -> audio_features MODE=4 RTL in Verilator 5.050',
      'template_sha256':hashlib.sha256(header.read_bytes()).hexdigest(),
      'feature_source_hashes':{str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest()
          for p in [ROOT/'rtl/audio_frontend.sv',ROOT/'rtl/reuse/low_pass_conv.sv',
                    ROOT/'rtl/reuse/fft_mag_sq.sv',ROOT/'rtl/audio_features.sv',
                    ROOT/'rtl/mel_weights.svh',ROOT/'assets/hamming.hex',*sorted((ROOT/'rtl/fft').glob('*.v'))]},
      'note':'Real H95 dataset recordings, not the group members. Frame metrics before voting; microphone/accent/room performance still needs hardware testing.'}
    (ROOT/'rtl/templates_training.json').write_text(json.dumps(report,indent=2)+'\n')
    print(json.dumps(report,indent=2))

if __name__=='__main__':main()
