// generated by train_templates.py: 16 templates, D=8, FW=16. Rows: class 0's NT templates, then class 1's, ...
localparam logic [7:0][15:0] TEMPLATES [0:15] = '{
    '{16'h09d4, 16'h0a0f, 16'h09ec, 16'h16af, 16'h0ad1, 16'h0bc3, 16'h0c40, 16'h4f7e},
    '{16'h0c9d, 16'h0d8e, 16'h0c22, 16'h1773, 16'h0d54, 16'h0c4d, 16'h0cf1, 16'h4cdb},
    '{16'h09c6, 16'h0c62, 16'h0cf3, 16'h1691, 16'h0d6b, 16'h0bf3, 16'h0be3, 16'h4ea4},
    '{16'h0a73, 16'h0d12, 16'h0c9d, 16'h1878, 16'h09e5, 16'h0bee, 16'h0d1d, 16'h4db6},
    '{16'h0b6a, 16'h0ba5, 16'h16a7, 16'h0a14, 16'h0be1, 16'h09da, 16'h4f8b, 16'h0a1d},
    '{16'h0c4b, 16'h0bd1, 16'h181a, 16'h09cc, 16'h0a40, 16'h09c9, 16'h4c48, 16'h0b57},
    '{16'h0d98, 16'h0ce8, 16'h1961, 16'h0b90, 16'h0b43, 16'h0cc0, 16'h4e93, 16'h0ac5},
    '{16'h0b48, 16'h0c84, 16'h182c, 16'h0d0c, 16'h0c4e, 16'h0d7a, 16'h4ed9, 16'h0b3f},
    '{16'h0afa, 16'h16f3, 16'h0bd1, 16'h0d11, 16'h0c95, 16'h4e6e, 16'h0a4b, 16'h0d2f},
    '{16'h0b29, 16'h178f, 16'h0d6a, 16'h0a0c, 16'h0d3d, 16'h4efa, 16'h0ba9, 16'h0b6a},
    '{16'h0b15, 16'h1774, 16'h0c16, 16'h0c93, 16'h0b05, 16'h4d2a, 16'h0bff, 16'h0c64},
    '{16'h0c33, 16'h1846, 16'h0aa7, 16'h0acb, 16'h0d3e, 16'h4d74, 16'h0b4b, 16'h0cbc},
    '{16'h166b, 16'h0b00, 16'h0cd7, 16'h0b54, 16'h4f6c, 16'h0b3d, 16'h0a18, 16'h09f4},
    '{16'h1612, 16'h0c01, 16'h0b14, 16'h0c63, 16'h4c66, 16'h0a13, 16'h0d30, 16'h0cdb},
    '{16'h15b0, 16'h0cc3, 16'h0aaa, 16'h0c85, 16'h4f48, 16'h0d42, 16'h0b86, 16'h0d20},
    '{16'h17c0, 16'h0c33, 16'h0a1e, 16'h0d76, 16'h4cf2, 16'h0da8, 16'h0b58, 16'h0bfe}
};
